<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function mostPopular()
    {
        $article = $this->createQueryBuilder('a')
            ->addSelect('count(a.id) as HIDDEN nb_a')
            ->leftJoin('a.likes', 'u')
            ->groupBy('a')
            ->addOrderBy('nb_a', 'desc')
            ->setMaxResults( 4 )
            ->getQuery()->getResult();
        ;

        return $article;
    }

    public function recentArticle()
    {
        $maxDate = new \DateTime('2 week ago');

        $recentA = $this->createQueryBuilder('ra')
            ->where('ra.articleDate >= :dateMax')
            ->setParameter('dateMax', $maxDate)
            ->getQuery()->getResult()
        ;

        return $recentA;
    }

    public function findArticle($name)
    {
        return $this->createQueryBuilder('a')
            ->where('a.name' == ':name')
            ->setParameter('name', $name)
            ->join('a.tags', 't')
            ->select('a, t')
            ->getQuery()
            ->getResult();
    }

}
