framework:
    csrf_protection: ~

security:
    providers:
    #Rassemble nos providers ci-dessous
        chain_provider:
            chain:
                providers: [practice_user_db_provider, practice_admin_db_provider]
        practice_user_db_provider:
            entity:
                class: AppBundle:User
        practice_admin_db_provider:
            entity:
                class: AppBundle:Admin

    #Gère l'encodage des mots de passe
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
        AppBundle\Entity\Admin:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            pattern:    ^/
            provider: chain_provider
            form_login:
                csrf_token_generator: security.csrf.token_manager
                login_path: login
                check_path: login
            #Permet de garder en mémoire une session
            remember_me:
                secret:   '%secret%'
                lifetime: 86400 # 1 day in seconds
                path:     /
                #Décommenter ci-dessous pour rendre automatique
                #always_remember_me: true
            logout:
                path:   /logout
                target: /


    #Permet de faire hériter un rôle des droits d'un autre rôle
    role_hierarchy:
            ROLE_ADMIN: ROLE_USER

    #Gère les permissions d'accès sur chaque url
    access_control:
        - { path: ^/(login|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }

    #Redirection en cas d'accès refusé
    access_denied_url: /login

