Thomas\TagBundle\Entity\Tag:
    type: entity
    table: null
    repositoryClass: Thomas\TagBundle\Repository\TagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
